name: CI Testing

on: [push, pull_request]

jobs:
  build:
    name: "CI Build"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build
      run: |
        npm install
        npm run build
        npm run test
